version: '3.8'

services:
  zone-fitness:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: green-zone-crossfit
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=zone-fitness"
      - "description=Green Zone CrossFit Website with Angular SSR"
    
    # Optional: Add volume for logs
    volumes:
      - ./logs:/app/logs
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: zone-fitness-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/ssl/certs
  #   depends_on:
  #     - zone-fitness
  #   restart: unless-stopped